# Ameba configuration for ToCry
# Only essential exceptions are kept here

# Allow not_nil! in test files for assertions and test setup
Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Excluded:
  - spec/**/*
  Enabled: true
  Severity: Warning
