#!/bin/bash
echo "  make build           - Build the tocry binary (generates clients first)"
echo "  make dev             - Build in development mode (faster)"
echo "  make watch           - Watch for changes and auto-rebuild server on port 3000"
echo "  make test            - Run all tests"
echo "  make check           - Run linter and tests"
echo ""
echo "Client Generation:"
echo "  make generate-clients - Generate OpenAPI spec and TypeScript/Crystal clients"
echo "  make generate-spec   - Generate only the OpenAPI spec"
echo ""
echo "Distribution & Release:"
echo "  make build-static    - Build static binaries for AMD64 and ARM64"
echo "  make docker          - Build and push Docker images"
echo "  make release         - Create a new release (bumps version, tags, uploads)"
echo ""
echo "Deployment:"
echo "  make deploy-site     - Deploy website to server"
echo ""
echo "Code Quality:"
echo "  make format          - Format Crystal code with crystal tool format"
echo "  make lint            - Run ameba linter"
echo ""
echo "Maintenance:"
echo "  make clean           - Remove build artifacts"
echo "  make install         - Install dependencies"
