require "file_utils" # For File.join and mkdir_p
require "./note"     # Lane contains Notes
require "json"       # For JSON serialization
require "sepia"      # For Sepia::Container

module ToCry
  class Lane < Sepia::Object
    include JSON::Serializable
    include Sepia::Container

    property name : String
    property notes : Array(Note)

    # Constructor that accepts a name, which will be used as display name.
    # sepia_id will be auto-generated by Sepia::Object
    def initialize(@name : String, @notes : Array(Note) = [] of Note)
    end

    # Constructor that accepts a sepia_id and name, for use when restoring existing lanes
    def initialize(sepia_id : String, @name : String, @notes : Array(Note) = [] of Note)
      @sepia_id = sepia_id
    end

    # Default constructor for deserialization (Sepia needs this)
    def initialize(@notes : Array(Note) = [] of Note)
      @name = "Untitled Lane" # Default name if not provided
    end

    def note_add(title : String, tags : Array(String) = [] of String, content : String = "", position : Int = 0, public : Bool = false, start_date : String? = nil, end_date : String? = nil, priority : Priority? = nil) : Note
      new_note = Note.new(title: title, tags: tags, content: content, public: public, start_date: start_date, end_date: end_date, priority: priority)
      actual_position = position.clamp(0, self.notes.size)

      self.notes.insert(actual_position, new_note)
      Log.info { "Note '#{new_note.title}' (ID: #{new_note.sepia_id}) added to lane '#{self.name}' at position #{actual_position}." }
      new_note
    rescue ex
      Log.error(exception: ex) { "Failed to add note '#{title}' to lane '#{self.name}'" }
      raise ex
    end

    # OpenAPI schema definition for Lane
    def self.schema
      {
        type:       "object",
        properties: {
          lane_id: {type: "string", description: "Unique identifier for the lane (UUID)"},
          name:    {type: "string", description: "Lane display name"},
          notes:   {
            type:        "array",
            description: "Array of notes in this lane",
            items:       {"$ref": "#/components/schemas/Note"},
          },
        },
        required: ["lane_id", "name"],
      }
    end
  end
end
